'тз11 новая ветка'
m00rl00n/java-filmorate pull request #33
Opened 2023-05-26 20:29 UTC by m00rl00n

2023-05-26 20:58 UTC, m00rl00n commented
Привет! у меня какие-то проблемы случились, несколько раз откатывала и перезаливала, поэтому табличку из промежуточного тз подгружала сейчас еще раз. Сдала ее вовремя, в табличке запись о взаимной проверке есть

2023-05-27 11:55 UTC, EugeneLenkevich requested changes
Привет, Виктория, спасибо за PR

В целом все отлично :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста. Ну и не думаю что стоит разивать пустыми строками аннотации и определение текста, это же единый логический блок

2023-05-27 11:55 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Добавление лайка фильму с айди " + id + " пользователем с айди " + userId);
Это логирование, кстати, лучше перенести в сервис. Это все таки описание бизнес-логики, а в контродллерах у нас обработка запросов :)

2023-05-27 11:55 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/MPAController.java
> +    public MPAController(MpaService mpaService) {
Можно не задавать руками конструктор, можно добавить аннотацию lombok @RequiredArgsConstroctor

единственное поля будут вот так выглядеть

private final MpaService mpaService;

2023-05-27 11:55 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmMapper.java
> +
Пустые строки тут лучше не оставлять, только путает :)

2023-05-27 11:55 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        return Objects.equals(id, film.id) &&
Вообще, сущность - это не просто объект, это представление строки таблицы базы данных, а строку таблицы однозначно определяет ее идентификатор, и потому, соотвественно, для сущностей equals и hashCode стоит определять на основе id (первичного ключа). 

Остальные поля, при этом, могут вообще быть разными, то есть могут существовать разные версии одного и того же объекта, но как это разруливатеся - это уже отдельная история.

2023-05-27 11:56 UTC, EugeneLenkevich commented
> Привет! у меня какие-то проблемы случились, несколько раз откатывала и перезаливала, поэтому табличку из промежуточного тз подгружала сейчас еще раз. Сдала ее вовремя, в табличке запись о взаимной проверке есть

Спасибо за уточнение, вроде как для ревью без раницы :)

2023-05-27 13:12 UTC, m00rl00n commented
Спасибо за ревью! Вроде все поправила, на счет equals и hashCode, ребята в беседе как-то обсуждали такую вариацию, может она подойдёт?  @EqualsAndHashCode(of = "id") Я на нее исправила, но если что, то могу вернуть обратно. Без ручных конструкторов код гораздо проще читается согласна, единственное, я добавила аннотацию вроде во всех местах, кроме контроллеров, почему то с аннотацией выпадают все тесты, поэтому там ручной оставила

2023-05-27 17:45 UTC, EugeneLenkevich commented
> Спасибо за ревью! Вроде все поправила, на счет equals и hashCode, ребята в беседе как-то обсуждали такую вариацию, может она подойдёт? @EqualsAndHashCode(of = "id") Я на нее исправила, но если что, то могу вернуть обратно. Без ручных конструкторов код гораздо проще читается согласна, единственное, я добавила аннотацию вроде во всех местах, кроме контроллеров, почему то с аннотацией выпадают все тесты, поэтому там ручной оставила

1. @EqualsAndHashCode(of = "id"), да, вполне, обычно так и делают
2. На счет констуктора - это просто синтаксический сахар, не критично :)

2023-05-27 17:46 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-06-03 22:53 UTC, merged